package com.example.tic_pv.Modelo;

public enum EstadosCuentas {
    ACTIVO, INACTIVO,
    CACHORRO, ADULTO, CANINO, FELINO, MACHO, HEMBRA,
    ACEPTADA, PENDIENTE, RECHAZADA, EN_REVISION, COMPLETADA,
    NOTIFICACION_ENVIADA, NOTIFICACION_LEIDA, NOTIFICACION_PROGRAMADA,
    NOTIFICACION_SOLICITUD_ADOPCION, NOTIFICACION_SEGUIMIENTO_ASIGNADO, NOTIFICACION_VACUNA,
    ARRENDADO, PROPIO,
    NO_FIRMADO, FIRMADO,
    VACUNA, DESPARASITACION

}
